import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { supabase } from "@src/utils/supabaseClient";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const [userName, setUserName] = useState("");

  useEffect(() => {
    const { logout } = router.query;
    logout && supabase.auth.signOut() && router.push("/");
  }, [router.query, router]);

  useEffect(() => {
    setUserName(supabase.auth.user()?.user_metadata.first_name);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>{`Welcome ${userName ?? ""}!`}</h1>
    </div>
  );
};

export default Home;
